# ==========    Default of Probe Automation V2.1    ==========

# Mode define  =>  0: Normal (BR+NA)  1: Skip Initial (BR+NA)  2: NA only
# Workflow define =>  0: Manual Move  1: Capture then Move next  2: Auto Capture and Move

Mode=0
Workflow=0

CreateSerialFolder=1

NA_IP=192.168.100.200
BR_IP=192.168.100.100
Project=fescue
Vendor=LGIT
Serial=

Output_S1P=0
Output_S2P=0
Output_S3P=1
Output_S4P=0

SavedFolder=
KeysightTool=

DUT_Point1=11
DUT_Point2=5
DUT_Point3=8
DUT_Point4=9
DUT_Point5=1
DUT_Point6=4
DUT_Point7=3
DUT_Point8=7
DUT_Point9=2
DUT_Point10=6
DUT_Point11=10